// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUurGXhDjSspSB9gNIGwB5ei8eXSmkY_A',
    appId: '1:1014558553358:web:052358252e62a7e563535f',
    messagingSenderId: '1014558553358',
    projectId: 'fasum-8e094',
    authDomain: 'fasum-8e094.firebaseapp.com',
    storageBucket: 'fasum-8e094.appspot.com',
    measurementId: 'G-74RHDC6SDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmoBnNqDDa_FbQHXLLKUJtkBHIe5AloUs',
    appId: '1:1014558553358:android:470184f6d184212c63535f',
    messagingSenderId: '1014558553358',
    projectId: 'fasum-8e094',
    storageBucket: 'fasum-8e094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhsL0m7PhSYLFHDiTTqTEVvvseTMr0EPk',
    appId: '1:1014558553358:ios:a3027c1bf93ab6d763535f',
    messagingSenderId: '1014558553358',
    projectId: 'fasum-8e094',
    storageBucket: 'fasum-8e094.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhsL0m7PhSYLFHDiTTqTEVvvseTMr0EPk',
    appId: '1:1014558553358:ios:9ee41c66f4b1b35e63535f',
    messagingSenderId: '1014558553358',
    projectId: 'fasum-8e094',
    storageBucket: 'fasum-8e094.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
